name: "CI / CD"

on:
  push:
    branches: [ "main", "feature/*", "bugfix/*" ]
    paths-ignore:
      - '.github/**.yml'
      - '!.github/workflows/ci.yml'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**.yml'
      - '!.github/workflows/ci.yml'

  workflow_dispatch:


jobs:
  strings:
    runs-on: ubuntu-latest
    outputs:
      build-dir: ${{ steps.strings.outputs.build-dir }}
      build-version: ${{ steps.strings.outputs.build-version }}
    steps:
      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-dir=build" >> "$GITHUB_OUTPUT"
          COMMIT_HASH=${{ github.sha }}
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "${{ github.event.repository.default_branch }}" ] && VERSION=latest
          VERSION="$VERSION+sha.${COMMIT_HASH:0:8}"
          echo VERSION=$VERSION
          echo "build-version=${VERSION}" >> "$GITHUB_OUTPUT"

  build-test-package:
    needs: [ strings ]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-latest, windows-latest, macos-latest ]
        preset: [ ci ]
        include:
          - os: ubuntu-latest
            preset: ci-x64-linux-static
          - os: ubuntu-latest
            preset: ci-x64-linux-dynamic
    steps:
      - name: Dependencies Windows
        if: runner.os == 'Windows'
        run: |
          choco install nsis

      - uses: actions/checkout@v5

      - uses: lukka/get-cmake@latest

      - uses: lukka/run-vcpkg@v11.5

      - name: Configure CMake
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        run: cmake --build ${{ needs.strings.outputs.build-dir }}/ci --config Debug

      - name: Test
        run: ctest --preset ci

      - name: Package
        run: cpack --preset ci -R "${{ needs.strings.outputs.build-version }}"

      - uses: actions/upload-artifact@v4
        with:
          name: learning-vcpkg-${{ matrix.os }}-${{ needs.strings.outputs.build-version }}
          path: ${{ needs.strings.outputs.build-dir }}/ci/learning-vcpkg-*
          if-no-files-found: error
